[package]
name = "jsonl_gzip_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
